version: "{build}"

# Source Config
clone_folder: c:\gopath\src\github.com\cristianoliveira\ergo

# Build host

environment:
  GOPATH: c:\gopath
  DEPTESTBYPASS501: 1
  GOVERSION: 1.8

init:
  - git config --global core.autocrlf input

# Build

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - choco install bzr
  - set Path=c:\go\bin;c:\gopath\bin;C:\Program Files (x86)\Bazaar\;C:\Program Files\Mercurial\%Path%
  - go version
  - go env

build: false

before_deploy:
  - go build
  - choco install 7zip
  - echo "%APPVEYOR_REPO_TAG_NAME% - ${appveyor_repo_tag_name}"
  - 7z a -tzip ergo-win.zip ergo*

deploy:
  tag: '${appveyor_repo_tag_name}'
  release: '${appveyor_repo_tag_name}'
  provider: GitHub
  auth_token:
    secure: "XlXg6r5idqW5O3qBiQHbZ73goavVOVKYaZx11GW7s8DO+M0/ERBImmXa4TAHbSOj"
  artifact:
    - path: '*.exe'
      name: ergo
      type: zip
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    # appveyor_repo_tag: true

test_script:
  - go test ./... -v
